# Generated by Django 3.2.22 on 2024-03-17 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='animal',
            fields=[
                ('animal_id', models.AutoField(primary_key=True, serialize=False)),
                ('animal_name', models.CharField(max_length=225)),
                ('animal_image', models.ImageField(upload_to='static/')),
            ],
        ),
        migrations.CreateModel(
            name='contact_details',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=225)),
                ('contact', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='forest_division',
            fields=[
                ('forest_division_id', models.AutoField(primary_key=True, serialize=False)),
                ('division_name', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('login_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=225)),
                ('password', models.CharField(max_length=225)),
                ('usertype', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='notifications',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=225)),
                ('description', models.CharField(max_length=225)),
                ('date', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=225)),
                ('lname', models.CharField(max_length=225)),
                ('place', models.CharField(max_length=225)),
                ('phone', models.CharField(max_length=225)),
                ('email', models.CharField(max_length=225)),
                ('forest_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wild_apk.forest_division')),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wild_apk.login')),
            ],
        ),
        migrations.CreateModel(
            name='preserved_animals',
            fields=[
                ('preserved_animal_id', models.AutoField(primary_key=True, serialize=False)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wild_apk.animal')),
            ],
        ),
        migrations.CreateModel(
            name='forest_station',
            fields=[
                ('forest_station_id', models.AutoField(primary_key=True, serialize=False)),
                ('station_name', models.CharField(max_length=225)),
                ('place', models.CharField(max_length=225)),
                ('contact_number', models.CharField(max_length=225)),
                ('forest_division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wild_apk.forest_division')),
            ],
        ),
        migrations.CreateModel(
            name='forest_officer',
            fields=[
                ('officer_id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=225)),
                ('lname', models.CharField(max_length=225)),
                ('place', models.CharField(max_length=225)),
                ('phone', models.CharField(max_length=225)),
                ('email', models.CharField(max_length=225)),
                ('designation', models.CharField(max_length=225)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wild_apk.login')),
            ],
        ),
        migrations.CreateModel(
            name='complaints',
            fields=[
                ('complaints_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=225)),
                ('description', models.CharField(max_length=225)),
                ('reply', models.CharField(max_length=225)),
                ('date', models.CharField(max_length=225)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wild_apk.user')),
            ],
        ),
        migrations.CreateModel(
            name='camera',
            fields=[
                ('camera_id', models.AutoField(primary_key=True, serialize=False)),
                ('camera_name', models.CharField(max_length=225)),
                ('latitude', models.CharField(max_length=225)),
                ('longitude', models.CharField(max_length=225)),
                ('forest_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wild_apk.forest_division')),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='forest_division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wild_apk.forest_division'),
        ),
        migrations.CreateModel(
            name='allocate',
            fields=[
                ('allocate_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=225)),
                ('forest_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wild_apk.forest_station')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wild_apk.forest_officer')),
            ],
        ),
        migrations.CreateModel(
            name='alert',
            fields=[
                ('alert_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=225)),
                ('date', models.CharField(max_length=225)),
                ('image', models.ImageField(upload_to='static/')),
                ('time', models.CharField(max_length=225)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wild_apk.camera')),
            ],
        ),
    ]
